/*
** 
** Copyright (C) 2019 Ambrose Gihan de Silva
** 
** Redistribution and use in source and binary forms, with or without 
** modification, are permitted provided that the following conditions are met:
** 
** 1. Redistributions of source code must retain the above copyright notice, this 
** list of conditions and the following disclaimer.
** 
** 2. Redistributions in binary form must reproduce the above copyright notice, 
** this list of conditions and the following disclaimer in the documentation 
** and/or other materials provided with the distribution.
** 
** THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND 
** ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED 
** WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE 
** DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR 
** ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**  (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
**  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND 
**  ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT 
**  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS 
**  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**  
 */
package com.shinkusoft.javapuzzle2;

/**
 *
 * @author Gihan
 */
public class PuzzleInfoPanel extends javax.swing.JPanel
{

    /**
     * Creates new form NewJPanel
     */
    public PuzzleInfoPanel()
    {
        initComponents();
        int solverMaxMovesValue = JavaPuzzle2.getToolsConfigData().getMaxSolverTreeSize();
        SolverMaxStepsValue.setText(Integer.toString(solverMaxMovesValue));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        costLabel = new javax.swing.JLabel();
        costValue = new javax.swing.JTextField();
        numMovesLabel = new javax.swing.JLabel();
        numMovesValue = new javax.swing.JTextField();
        SolverMoveTreeLabel = new javax.swing.JLabel();
        SolverMoveTreeValue = new javax.swing.JTextField();
        HistoryLengthLabel = new javax.swing.JLabel();
        MoveHistoryLength = new javax.swing.JTextField();
        LeftHorizontalFiller = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        SolverMethodLabel = new javax.swing.JLabel();
        SolverMethodNameValue = new javax.swing.JTextField();
        SolverMaxStepsValue = new javax.swing.JTextField();
        SolverMaxStepsLabel = new javax.swing.JLabel();
        SolverStepsLabel = new javax.swing.JLabel();
        SolverStepsValue = new javax.swing.JTextField();
        CurrentStatusLabel = new javax.swing.JLabel();
        CurrentStatusValue = new javax.swing.JTextField();
        SolverTimeLabel = new javax.swing.JLabel();
        SolverTimeValue = new javax.swing.JTextField();

        setBackground(new java.awt.Color(75, 116, 150));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Solution information:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 20))); // NOI18N
        setAutoscrolls(true);
        setFocusable(false);
        setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        setMaximumSize(new java.awt.Dimension(32767, 106));
        setMinimumSize(new java.awt.Dimension(411, 106));
        setLayout(new java.awt.GridBagLayout());

        costLabel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        costLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        costLabel.setText("Current state cost: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 16, 0, 0);
        add(costLabel, gridBagConstraints);

        costValue.setEditable(false);
        costValue.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        costValue.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        costValue.setText("0");
        costValue.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 42;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 4, 0, 0);
        add(costValue, gridBagConstraints);

        numMovesLabel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        numMovesLabel.setText("Moves:");
        numMovesLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.insets = new java.awt.Insets(27, 6, 0, 20);
        add(numMovesLabel, gridBagConstraints);

        numMovesValue.setEditable(false);
        numMovesValue.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        numMovesValue.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numMovesValue.setText("0");
        numMovesValue.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 42;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 5, 0, 0);
        add(numMovesValue, gridBagConstraints);

        SolverMoveTreeLabel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        SolverMoveTreeLabel.setText("Solver Move Tree Size:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 16, 21, 0);
        add(SolverMoveTreeLabel, gridBagConstraints);

        SolverMoveTreeValue.setEditable(false);
        SolverMoveTreeValue.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        SolverMoveTreeValue.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SolverMoveTreeValue.setText("0");
        SolverMoveTreeValue.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        SolverMoveTreeValue.setPreferredSize(new java.awt.Dimension(105, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 44;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 4, 21, 0);
        add(SolverMoveTreeValue, gridBagConstraints);

        HistoryLengthLabel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        HistoryLengthLabel.setText("Move history size:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 16, 21, 0);
        add(HistoryLengthLabel, gridBagConstraints);

        MoveHistoryLength.setEditable(false);
        MoveHistoryLength.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        MoveHistoryLength.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        MoveHistoryLength.setText("0");
        MoveHistoryLength.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 42;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 4, 21, 0);
        add(MoveHistoryLength, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        add(LeftHorizontalFiller, gridBagConstraints);

        SolverMethodLabel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        SolverMethodLabel.setText("Solver Method:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 16, 21, 0);
        add(SolverMethodLabel, gridBagConstraints);

        SolverMethodNameValue.setEditable(false);
        SolverMethodNameValue.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SolverMethodNameValue.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SolverMethodNameValue.setText("Uniform Cost search");
        SolverMethodNameValue.setAutoscrolls(false);
        SolverMethodNameValue.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        SolverMethodNameValue.setMinimumSize(new java.awt.Dimension(150, 28));
        SolverMethodNameValue.setPreferredSize(new java.awt.Dimension(150, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(19, 4, 21, 10);
        add(SolverMethodNameValue, gridBagConstraints);

        SolverMaxStepsValue.setBackground(new java.awt.Color(240, 240, 240));
        SolverMaxStepsValue.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        SolverMaxStepsValue.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SolverMaxStepsValue.setText("0");
        SolverMaxStepsValue.setToolTipText("");
        SolverMaxStepsValue.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        SolverMaxStepsValue.setPreferredSize(new java.awt.Dimension(130, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        add(SolverMaxStepsValue, gridBagConstraints);

        SolverMaxStepsLabel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        SolverMaxStepsLabel.setText("Maximum Steps:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        add(SolverMaxStepsLabel, gridBagConstraints);

        SolverStepsLabel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        SolverStepsLabel.setText("Solver Steps:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        add(SolverStepsLabel, gridBagConstraints);

        SolverStepsValue.setEditable(false);
        SolverStepsValue.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        SolverStepsValue.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SolverStepsValue.setText("0");
        SolverStepsValue.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        SolverStepsValue.setPreferredSize(new java.awt.Dimension(80, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(2, 3, 0, 8);
        add(SolverStepsValue, gridBagConstraints);

        CurrentStatusLabel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        CurrentStatusLabel.setText("Current Status:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        add(CurrentStatusLabel, gridBagConstraints);

        CurrentStatusValue.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        CurrentStatusValue.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CurrentStatusValue.setText("idle");
        CurrentStatusValue.setToolTipText("");
        CurrentStatusValue.setMinimumSize(new java.awt.Dimension(80, 28));
        CurrentStatusValue.setPreferredSize(new java.awt.Dimension(80, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        add(CurrentStatusValue, gridBagConstraints);

        SolverTimeLabel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        SolverTimeLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        SolverTimeLabel.setText("Elapsed Time (s):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        add(SolverTimeLabel, gridBagConstraints);

        SolverTimeValue.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        SolverTimeValue.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SolverTimeValue.setText("0.0");
        SolverTimeValue.setPreferredSize(new java.awt.Dimension(130, 28));
        SolverTimeValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SolverTimeValueActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 3;
        add(SolverTimeValue, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void SolverTimeValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SolverTimeValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SolverTimeValueActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CurrentStatusLabel;
    protected javax.swing.JTextField CurrentStatusValue;
    private javax.swing.JLabel HistoryLengthLabel;
    private javax.swing.Box.Filler LeftHorizontalFiller;
    protected javax.swing.JTextField MoveHistoryLength;
    private javax.swing.JLabel SolverMaxStepsLabel;
    protected javax.swing.JTextField SolverMaxStepsValue;
    private javax.swing.JLabel SolverMethodLabel;
    protected javax.swing.JTextField SolverMethodNameValue;
    private javax.swing.JLabel SolverMoveTreeLabel;
    protected javax.swing.JTextField SolverMoveTreeValue;
    private javax.swing.JLabel SolverStepsLabel;
    protected javax.swing.JTextField SolverStepsValue;
    private javax.swing.JLabel SolverTimeLabel;
    protected javax.swing.JTextField SolverTimeValue;
    private javax.swing.JLabel costLabel;
    protected javax.swing.JTextField costValue;
    private javax.swing.JLabel numMovesLabel;
    protected javax.swing.JTextField numMovesValue;
    // End of variables declaration//GEN-END:variables
}
